//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CariHesap.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int kullaniciID { get; set; }
        public string adi { get; set; }
        public string sifre { get; set; }
    }
}
