//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CariHesap.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.Satis = new HashSet<Satis>();
        }
    
        public int urunID { get; set; }
        public int kategoriID { get; set; }
        public string urunAdi { get; set; }
        public int gelisFıyati { get; set; }
        public int satisFiyati { get; set; }
        public int stok { get; set; }
        public System.DateTime eklenmeTarihi { get; set; }
        public bool durum { get; set; }
        public string aciklama { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satis> Satis { get; set; }
    }
}
